version: "3.0"
services:
  client:
    container_name: client
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    tty: true
    cap_add:
    - NET_ADMIN
  server:
    container_name: server
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    ports:
      - "8001:8001"
    cap_add:
    - NET_ADMIN
