FROM python:3.10.5

WORKDIR /app
RUN apt-get update && \
    apt-get install iproute2 iputils-ping iptables -y

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD /bin/bash
